SAMPLE_TICKETS = [
    # ── ACCESS & AUTHENTICATION (12 tickets) ──────────────────────────────
    {
        "id": "TKT-001",
        "subject": "Locked out of Okta - can't access anything",
        "body": "I tried logging in this morning and got locked out after 3 failed attempts. I have a board presentation in 2 hours and can't get into any of my apps. Please help ASAP.",
        "submitter": "Sarah Chen",
        "department": "Sales",
        "submitted_at": "2024-04-09 08:14:00",
    },
    {
        "id": "TKT-002",
        "subject": "MFA app stopped working after I got a new phone",
        "body": "I got a new iPhone over the weekend and the Okta Verify app isn't working. I set it up on the new phone but it keeps saying the code is wrong. Can't log in to anything.",
        "submitter": "Marcus Webb",
        "department": "Engineering",
        "submitted_at": "2024-04-09 08:31:00",
    },
    {
        "id": "TKT-003",
        "subject": "Need access to Salesforce for new role",
        "body": "I was promoted to Account Executive last week. My manager Jake Torres approved it and said to contact IT. I need Salesforce access with AE-level permissions. Current role was SDR.",
        "submitter": "Priya Nair",
        "department": "Sales",
        "submitted_at": "2024-04-09 08:45:00",
    },
    {
        "id": "TKT-004",
        "subject": "Password reset - forgot it over the holidays",
        "body": "I've been on PTO for two weeks and forgot my laptop password. I can get into Okta on my phone but Windows is locked.",
        "submitter": "Tom Bradley",
        "department": "Marketing",
        "submitted_at": "2024-04-09 08:52:00",
    },
    {
        "id": "TKT-005",
        "subject": "Can't access shared Google Drive folder - says no permission",
        "body": "My team shared a folder called Q2 Campaign Assets but when I click the link it says I don't have access. I'm listed in the team Slack channel so I should have it.",
        "submitter": "Lena Hoffman",
        "department": "Marketing",
        "submitted_at": "2024-04-09 09:10:00",
    },
    {
        "id": "TKT-006",
        "subject": "GitHub access - contractor needs repo permissions",
        "body": "We have a contractor starting today, Arjun Mehta (arjun@devpartners.io). He needs read access to the frontend-v2 and api-core repos. Duration is 3 months. My manager approved.",
        "submitter": "Dana Reyes",
        "department": "Engineering",
        "submitted_at": "2024-04-09 09:22:00",
    },
    {
        "id": "TKT-007",
        "subject": "Offboarding - employee last day today",
        "body": "James Okafor (jokafor@company.com) in Finance has his last day today, April 9. Please disable all access at 5pm PST. He's returning his laptop via FedEx tomorrow.",
        "submitter": "Rachel Kim",
        "department": "HR",
        "submitted_at": "2024-04-09 09:35:00",
    },
    {
        "id": "TKT-008",
        "subject": "SSO not working for Workday",
        "body": "When I click the Workday tile in Okta it spins for a few seconds then gives an error: 'SAML response rejected.' Other apps work fine. I need to submit my expenses by EOD.",
        "submitter": "Carlos Jimenez",
        "department": "Finance",
        "submitted_at": "2024-04-09 09:48:00",
    },
    {
        "id": "TKT-009",
        "subject": "New hire starting Monday - need full setup",
        "body": "We have a new hire starting Monday 4/14: Alex Tran, Senior Designer, Design team. He'll need MacBook Pro, Adobe CC, Figma, Slack, Google Workspace, Notion, and Jira. Manager is Wei Liu.",
        "submitter": "Maya Patel",
        "department": "HR",
        "submitted_at": "2024-04-09 09:55:00",
    },
    {
        "id": "TKT-010",
        "subject": "Account showing suspended in Okta",
        "body": "I got an email saying my account was suspended due to inactivity but I've been using it every day. I can't log in. Did something go wrong?",
        "submitter": "Brian Foster",
        "department": "Product",
        "submitted_at": "2024-04-09 10:12:00",
    },
    {
        "id": "TKT-011",
        "subject": "Need admin access to Google Analytics",
        "body": "I've been asked to own our GA4 reporting going forward. Currently have read-only access. Need admin or editor level. My manager (Christina Park) has approved this.",
        "submitter": "Jordan Ellis",
        "department": "Marketing",
        "submitted_at": "2024-04-09 10:28:00",
    },
    {
        "id": "TKT-012",
        "subject": "Slack showing deactivated - can't message anyone",
        "body": "I opened Slack this morning and it says my account is deactivated. I can still get emails though. I have a standup in 20 minutes and can't communicate with my team.",
        "submitter": "Simone Alvarez",
        "department": "Design",
        "submitted_at": "2024-04-09 10:41:00",
    },

    # ── HARDWARE (8 tickets) ────────────────────────────────────────────────
    {
        "id": "TKT-013",
        "subject": "MacBook won't turn on",
        "body": "I closed my laptop last night normally and this morning it won't boot. Holding the power button does nothing. It was at 60% battery when I closed it. I have a client call in an hour.",
        "submitter": "Nina Torres",
        "department": "Sales",
        "submitted_at": "2024-04-09 07:58:00",
    },
    {
        "id": "TKT-014",
        "subject": "External monitor not detected",
        "body": "Got a new Dell monitor from the office supply order. Plugged it in via USB-C hub and MacBook doesn't detect it at all. Tried restarting. My old monitor worked fine on the same setup.",
        "submitter": "Derek Walsh",
        "department": "Engineering",
        "submitted_at": "2024-04-09 10:05:00",
    },
    {
        "id": "TKT-015",
        "subject": "Laptop screen cracked - need replacement",
        "body": "I dropped my laptop this morning and the screen is cracked. It still works but hard to see half the screen. I have it in a protective case now. Do I need to come to the office to swap?",
        "submitter": "Fatima Al-Hassan",
        "department": "Operations",
        "submitted_at": "2024-04-09 10:55:00",
    },
    {
        "id": "TKT-016",
        "subject": "Keyboard keys sticking - coffee spill",
        "body": "Coffee spilled on my keyboard this morning. Keys G, H, and space are sticking. I wiped it off and let it dry but still happening. Can I get a replacement keyboard or do I need a new laptop?",
        "submitter": "Ryan Park",
        "department": "Product",
        "submitted_at": "2024-04-09 11:08:00",
    },
    {
        "id": "TKT-017",
        "subject": "Headset microphone not working on Zoom calls",
        "body": "My Jabra headset mic stopped picking up audio yesterday. Others can't hear me on calls. The speakers still work fine. I've tried unplugging and replugging. Windows shows it as connected.",
        "submitter": "Aisha Ogunwale",
        "department": "Customer Success",
        "submitted_at": "2024-04-09 11:22:00",
    },
    {
        "id": "TKT-018",
        "subject": "Request for second monitor - WFH setup",
        "body": "I've been working from home for 6 months and doing everything on my laptop screen. Would it be possible to get a company monitor for home use? I'm doing a lot of data work across multiple windows.",
        "submitter": "Gregory Moss",
        "department": "Data",
        "submitted_at": "2024-04-09 11:40:00",
    },
    {
        "id": "TKT-019",
        "subject": "Laptop running extremely hot and fan very loud",
        "body": "For the past few days my MacBook has been running very hot and the fan is constantly at full speed. Performance has also slowed down. I haven't installed anything new recently.",
        "submitter": "Yuki Tanaka",
        "department": "Engineering",
        "submitted_at": "2024-04-09 12:01:00",
    },
    {
        "id": "TKT-020",
        "subject": "Mouse and keyboard not working after Windows update",
        "body": "Windows updated overnight and now neither my USB mouse nor keyboard are working when I boot up. I can only interact with the machine if I plug in a different USB keyboard. Everything worked before the update.",
        "submitter": "Colette Marchand",
        "department": "Finance",
        "submitted_at": "2024-04-09 12:18:00",
    },

    # ── SOFTWARE & APPS (6 tickets) ─────────────────────────────────────────
    {
        "id": "TKT-021",
        "subject": "Zoom keeps crashing mid-call",
        "body": "Zoom has crashed 3 times today during calls. It just closes with no error. I'm on the latest version. Other apps seem fine. I'm presenting to a customer tomorrow and very concerned.",
        "submitter": "Brendan Cole",
        "department": "Sales",
        "submitted_at": "2024-04-09 12:35:00",
    },
    {
        "id": "TKT-022",
        "subject": "Need Figma license - current account is free tier",
        "body": "I joined the design team 2 months ago and I'm still on the free Figma tier. I can't access shared team files or use certain features. Can I be added to the company license?",
        "submitter": "Isabelle Grant",
        "department": "Design",
        "submitted_at": "2024-04-09 12:52:00",
    },
    {
        "id": "TKT-023",
        "subject": "Excel keeps showing 'not responding' when opening large files",
        "body": "Any Excel file over 10MB causes Excel to hang for 5+ minutes before opening. This started last week. Our quarterly reports are 25MB+ and I can't work with them. On Windows 11.",
        "submitter": "Patricia Huang",
        "department": "Finance",
        "submitted_at": "2024-04-09 13:08:00",
    },
    {
        "id": "TKT-024",
        "subject": "Requesting Grammarly Business license",
        "body": "Several people on my team already have Grammarly Business. It would significantly help my work communicating with external partners. Is there budget for another seat?",
        "submitter": "Omar Abdullah",
        "department": "Legal",
        "submitted_at": "2024-04-09 13:25:00",
    },
    {
        "id": "TKT-025",
        "subject": "Jira tickets not loading - blank screen",
        "body": "Jira has been showing a blank white screen for the last hour when I click into any ticket. The board view loads but individual tickets don't. Affects all my team members too - this might be org-wide.",
        "submitter": "Sam Nguyen",
        "department": "Engineering",
        "submitted_at": "2024-04-09 13:40:00",
    },
    {
        "id": "TKT-026",
        "subject": "Need Adobe Acrobat Pro - currently using free version",
        "body": "I need to edit PDFs and compress files regularly for contract work. The free version doesn't allow editing. Can I get an Acrobat Pro license? My manager has approved the request.",
        "submitter": "Veronica Strand",
        "department": "Legal",
        "submitted_at": "2024-04-09 13:55:00",
    },

    # ── NETWORK & CONNECTIVITY (4 tickets) ─────────────────────────────────
    {
        "id": "TKT-027",
        "subject": "VPN won't connect - GlobalProtect error",
        "body": "Getting error 'Unable to connect to gateway' on GlobalProtect. This started this morning. I'm trying to access internal tools I can only reach via VPN. Working from a hotel in Chicago.",
        "submitter": "Kevin Larsson",
        "department": "Sales",
        "submitted_at": "2024-04-09 14:10:00",
    },
    {
        "id": "TKT-028",
        "subject": "Video calls dropping every 10-15 minutes",
        "body": "I've been getting disconnected from every Zoom and Google Meet call after about 10-15 minutes. Rejoining works but it's disruptive. Internet speed tests show 200mbps so bandwidth isn't the issue. Using ethernet.",
        "submitter": "Tamara Osei",
        "department": "Customer Success",
        "submitted_at": "2024-04-09 14:28:00",
    },
    {
        "id": "TKT-029",
        "subject": "Can't reach internal wiki - connection refused",
        "body": "Trying to access our internal Confluence at confluence.internal.company.com and getting 'connection refused'. This was working yesterday. VPN is connected. Other internal tools work.",
        "submitter": "Lucas Ferrari",
        "department": "Product",
        "submitted_at": "2024-04-09 14:45:00",
    },
    {
        "id": "TKT-030",
        "subject": "Office WiFi extremely slow in the east wing",
        "body": "The WiFi in the east wing of the SF office has been unusably slow for 3 days. Measured around 2mbps vs the usual 300+. The west wing is fine. About 15 people are affected. We've all tried different devices.",
        "submitter": "Chloe Bergmann",
        "department": "Operations",
        "submitted_at": "2024-04-09 15:02:00",
    },
]
